[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "driftwatch"
version = "3.0.0"
dependencies = [
    "boto3",
    "typer",
    "groq",
    "python-telegram-bot",
    "psycopg2-binary"
]

[project.scripts]
driftwatch = "driftwatch.cli:app"

[tool.setuptools.packages.find]
include = ["driftwatch*", "drift_engine*"]