apiVersion: batch/v1
kind: CronJob
metadata:
  name: driftwatch-cronjob
spec:
  schedule: "*/15 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          hostNetwork: true
          dnsPolicy: Default
          containers:
          - name: driftwatch-engine
            image: driftwatch:latest
            imagePullPolicy: Never
            command:
            - "python"
            - "/app/drift_engine/core.py"
            envFrom:
            - secretRef:
                name: driftwatch-env
          restartPolicy: OnFailure