apiVersion: batch/v1
kind: CronJob
metadata:
  name: driftwatch-cronjob
spec:
  schedule: "*/15 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          securityContext:
            runAsNonRoot: true
            runAsUser: 10001
            runAsGroup: 10001
            fsGroup: 10001
          dnsPolicy: ClusterFirst
          containers:
          - name: driftwatch-engine
            image: driftwatch:latest
            imagePullPolicy: IfNotPresent
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: false
              capabilities:
                drop:
                - ALL
            command:
            - "driftwatch"
            - "scan"
            - "--region"
            - "ap-south-1"
            - "--fail-on"
            - "CRITICAL"
            envFrom:
            - secretRef:
                name: driftwatch-env
          restartPolicy: OnFailure